# Generated by Django 5.2.4 on 2025-07-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='location',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
